_target_: src.models.dlib300w_module.DlibLiModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.0001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: True
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_resnet.SimpleResnet
  model_name: "resnet50"
  weights: 